// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "balnce-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://balnce-dev.s3-website.us-east-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-2:88edcd17-4a63-428d-af3b-1f7d8c4be0d7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_pQjKfTOY3",
    "aws_user_pools_web_client_id": "4nti4fvuudqprpeiovqi0vf998"
};


export default awsmobile;
