// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a1c967c8-9e3a-4ab8-8b57-3a14342dba54",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_sPw99hymd",
    "aws_user_pools_web_client_id": "1t418knbp2149705a4qd7ndt6",
    "aws_appsync_graphqlEndpoint": "https://5tsb2o2jnna2bmookpjr6gjy7y.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
