// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a9f6b5fb-fcb6-4a6c-97ef-361d2c5d3bbd",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_CjJmC8k1y",
    "aws_user_pools_web_client_id": "6s6ges1aree0roep2sf4kookl3",
    "aws_appsync_graphqlEndpoint": "https://eqkejw5gq5bunolkzhxnybf2bm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
